# Generated by Django 2.1.5 on 2021-01-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0002_auto_20210105_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='cellf',
        ),
    ]
